_meta_: {}
bundle_root: /workspace/workspace-kits23/exp/kits23-part1-seg3d/segresnet_0
ckpt_path: $@bundle_root + '/model'
mlflow_tracking_uri: $@ckpt_path + '/mlruns/'
mlflow_experiment_name: Auto3DSeg
data_file_base_dir: /workspace/workspace-kits23/kits23
data_list_file_path: /workspace/workspace-kits23/exp/kits23-part1-seg3d/kits23_folds-part1.json
modality: ct
fold: 0
input_channels: 1
output_classes: 3
class_names: [kidney_and_mass, mass, tumor]
class_index:
- [1, 2, 3]
- [2, 3]
- [2]
debug: false
ckpt_save: true
cache_rate: null
roi_size: [64, 64, 64]
auto_scale_allowed: false
auto_scale_batch: true
auto_scale_roi: false
auto_scale_filters: false
quick: false
channels_last: true
validate_final_original_res: true
calc_val_loss: false
amp: true
log_output_file: null
cache_class_indices: null
early_stopping_fraction: 0.001
determ: false
orientation_ras: true
crop_foreground: true
learning_rate: 0.0002
batch_size: 1
num_images_per_batch: 1
num_epochs: 600
num_warmup_epochs: 3
sigmoid: true
resample: true
resample_resolution: [0.78125, 0.78125, 0.78125]
crop_mode: ratio
normalize_mode: range
intensity_bounds: [-51.62923509247449, 230.72855548469389]
num_epochs_per_validation: null
num_epochs_per_saving: 1
num_workers: 4
num_steps_per_image: null
num_crops_per_image: 1
loss: {_target_: DiceCELoss, include_background: true, squared_pred: true, smooth_nr: 0,
  smooth_dr: 1.0e-05, softmax: $not @sigmoid, sigmoid: $@sigmoid, to_onehot_y: $not
    @sigmoid}
optimizer: {_target_: torch.optim.AdamW, lr: '@learning_rate', weight_decay: 1.0e-05}
network:
  _target_: SegResNetDS
  init_filters: 32
  blocks_down: [1, 2, 2, 4, 4]
  norm: INSTANCE_NVFUSER
  in_channels: '@input_channels'
  out_channels: '@output_classes'
  dsdepth: 4
finetune: {enabled: false, ckpt_name: $@bundle_root + '/model/model.pt'}
validate: {enabled: false, ckpt_name: $@bundle_root + '/model/model.pt', output_path: $@bundle_root
    + '/prediction_validation', save_mask: false, invert: true}
infer: {enabled: false, ckpt_name: $@bundle_root + '/model/model.pt', output_path: $@bundle_root
    + '/prediction_' + @infer#data_list_key, data_list_key: testing}
anisotropic_scales: false
spacing_median: [0.8112734258174896, 0.8112734258174896, 3.875]
spacing_lower: [0.4534077376127243, 0.4534077376127243, 0.5]
spacing_upper: [0.9765625, 0.9765625, 5.0]
image_size_mm_median: [415.3719940185547, 415.3719940185547, 446.0]
image_size_mm_90: [499.0, 499.0, 632.9]
image_size: [638, 638, 810]
algos: segresnet
num_fold: 1
ensemble: false
work_dir: exp/kits23-part1-seg3d
